### ISSUE TITLE
[Enhancement] Negative reward weight for invalid mech calls should be configurable as an environment variable

### ISSUE THREAD

**Issue by dagacha** [valory-xyz/trader#120]
Currently the negative reward is set to be simply the Mech price. This negative reward could be configurable as an env variable NEGATIVE_REWARD so that the service owner/operator has flexibility to choose. Options that may make sense:
- NEGATIVE_REWARD is the same for every mech tool type
- NEGATIVE_REWARD represents a factor that multiples the value of every mech call. For example, if NEGATIVE_REWARD = 2 then the mech tool is punished in the policy with twice the price paid for the mech call.

**Comment by Adamantios** [comment]
Instead of `-(penalty * multiplier)` it should be `-penalty * multiplier`:

https://github.com/valory-xyz/trader/blob/6882fc235a1a5d956f8d60c6355708df88ea33e6/packages/valory/skills/decision_maker_abci/behaviours/blacklisting.py#L56-L57

**Comment by Adamantios** [comment]
> Instead of `-penalty * multiplier` it should be `-(penalty * multiplier)`:
> 
> https://github.com/valory-xyz/trader/blob/6882fc235a1a5d956f8d60c6355708df88ea33e6/packages/valory/skills/decision_maker_abci/behaviours/blacklisting.py#L56-L57

Sorry, this comment does not make much sense, closing the issue again as the calculation is fine.
