### ISSUE TITLE
[Staking] Service should attempt call the checkpoint even if mech call has failed.

### ISSUE THREAD

**Issue by jmoreira-valory** [valory-xyz/trader#138]
If the Mech call fails, the service should continue with the rest of the business logic, in particular calling the checkpoint. Currently, the checkpoint is only called after a successful Mech response.

However, this presents the following issue:
1- Service makes enough calls to the Mech to be eligible, but checkpoint has not been reached.
2- At this point Mech stops responding, therefore
3- Service will not call checkpoint after this point, even after the liveness period has passed.

This leads to a situation where the service is elegible for rewards, the liveness period has passed, but the service is not calling checkpoint.

**Comment by DavidMinarsch** [comment]
Only one service has to call checkpoint. I think we can safely close this issue. It is not a pressing concern.
