### ISSUE TITLE
[Enhancement] Avoid to repeatedly check the same markets when redeeming

### ISSUE THREAD

**Issue by Adamantios** [valory-xyz/trader#143]
The redeeming round always needs to check all the events from the block on which it first placed a bet.

This can be improved by storing the condition ids of the redeemed positions in the synchronized data.

**Comment by DavidMinarsch** [comment]
Beyond just storing in the synchronized data (which is important for a given agent run), it would be useful to not recheck everything when turning off and on the agent again. Maybe we can assume that the default behaviour only filters from the point of the last redeem? Although there'd be risks in this. We could also simply store the point of last redemption?

**Comment by Adamantios** [comment]
> We could also simply store the point of last redemption?

The risk stems from the possibility that redeeming market A does not necessarily imply that it is older than market B which may not have been finalized yet.

Therefore, we can only store the condition ids of the redeemed positions as a solution. That way, we can filter the corresponding markets out before searching for the oldest one which will define the block from which the filtering operation will start.

**Comment by Adamantios** [comment]
Reopening this as we currently do not have support for persisting the condition ids across runs (as suggested in https://github.com/valory-xyz/trader/issues/143#issuecomment-1817889341), but only across periods (added in #151).

**Comment by Adamantios** [comment]
Closing this issue as it is irrelevant after #172.

We are not using filtering anymore for the redeeming. Instead, we are using the indexed data provided by the subgraphs.
