### ISSUE TITLE
[Bug] Agent gets stuck with warning "The given transaction has not been reverted!"

### ISSUE THREAD

**Issue by dagacha** [valory-xyz/trader#164]
Full warning. message

`[2023-11-29 10:34:17,573] [WARNING] [agent] The given transaction has not been reverted!
tx: {'hash': '0xdadbd81ee22a26eaf25abd706b1890485e23fcab3ac5cea866d075ce8b3ff4aa', 'nonce': 1506, 'blockHash': '0x11a262853f72eea39fd89ecd5a7065a81229e4efa2130076c21717b52baac085', 'blockNumber': 31188796, 'transactionIndex': 0, 'from': '0x215D419fD833763B6B8AEbb70674C6d9F906E445', 'to': '0x1bDE46E6a3128fFF5f0b94911bf6C447aD909215', 'value': 0, 'gasPrice': 3000000013, 'maxPriorityFeePerGas': 3000000000, 'maxFeePerGas': 4000000000, 'gas': 262030, 'input': '0x6a7612020000000000000000000000005add592ce0a1b5dcecebb5dcac086cd9f9e3ea5c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000014000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001800000000000000000000000000000000000000000000000000000000000000004c2c4c5c1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000041b79cb1f0d760953ccbd72c773c09fde9c71417d737b69802cf5847b4e120cfa178fa6336ddf081524b23a784303973c52234f135e24a98acbc8bcbb406bb339b1c00000000000000000000000000000000000000000000000000000000000000', 'chainId': 100, 'type': 2, 'accessList': [], 'v': 1, 's': '0x07a7e6e0d6353eb11bf994e7089ecc638dc12f893a7192ff429068ead4967be9', 'r': '0x05f34d5689d0249aeb311047674037eef73a267aca9c3e699a0bbbf9baf1636a', 'yParity': 1}
`

**Comment by Adamantios** [comment]
Moved the issue to the core as it is not related to the service.
