### ISSUE TITLE
Move custom strategy

### ISSUE THREAD

**Issue by Adamantios** [valory-xyz/trader#229]
I think this custom strategy should not be under Valory packages.

_Originally posted by @Adamantios in https://github.com/valory-xyz/trader/pull/225#discussion_r1502620650_

**Comment by Adamantios** [comment]
Tried to address this issue, however when using `0xmikemikemike` as an author's name, the framework reports:

> Error: Value 0xmikemikemike does not match the regular expression re.compile('[a-z_][a-z0-9_]{0,127}')

@angrybayblade Can we alleviate this constraint?

**Comment by angrybayblade** [comment]
This piece of code is in very deep of the core, changing this might lead to a lot of things  breaking unnecessarily. For more context see  https://github.com/fetchai/agents-aea/issues/1727 and https://github.com/fetchai/agents-aea/pull/1880
