### ISSUE TITLE
[Question] Explanation about interaction with conditional_tokens contract

### ISSUE THREAD

**Issue by gabrielfior** [valory-xyz/trader#236]
I'm studying the redeeming positions interaction and one method is not clear to me:

```
# packages/valory/skills/decision_maker_abci/behaviours/reedem.py
def _check_already_redeemed_via_events(self) -> WaitableConditionType:
[...]
result = yield from self._conditional_tokens_interact(
                contract_callable="check_redeemed",
                data_key="payouts",
                placeholder=get_name(RedeemBehaviour.payouts_batch),
                redeemer=safe_address_lower,
                from_block=from_block,
                to_block=to_block,
                timeout=self.params.contract_timeout,
                **kwargs,
            )
[...]
def _conditional_tokens_interact(
        self, contract_callable: str, data_key: str, placeholder: str, **kwargs: Any
    ) -> WaitableConditionType:
        """Interact with the conditional tokens contract."""
        status = yield from self.contract_interact(
            performative=ContractApiMessage.Performative.GET_RAW_TRANSACTION,  # type: ignore
            contract_address=self.params.conditional_tokens_address,
            contract_public_id=ConditionalTokensContract.contract_id,
            contract_callable=contract_callable,
            data_key=data_key,
            placeholder=placeholder,
            **kwargs,
        )
```
The ConditionalTokens contract address (on Gnosis Mainnet) is https://gnosisscan.io/address/0xceafdd6bc0bef976fdcd1112955828e00543c0ce#code). I couldn't find any function that resembles `check_redeemed` or similar, hence would appreciate a bit more context for this behaviour.

Thanks!

**Comment by Adamantios** [comment]
Hey @gabrielfior. The `contract_callable` that you see in the code refers to a callable of the [ConditionalTokensContract](https://github.com/valory-xyz/trader/blob/v0.12.8/packages/valory/contracts/conditional_tokens/contract.py#L35), which is an `open-aea` [contract](https://open-aea.docs.autonolas.tech/contract/), not the on-chain contract.

You may find the implementation of the `check_redeemed` method [here](https://github.com/valory-xyz/trader/blob/v0.12.8/packages/valory/contracts/conditional_tokens/contract.py#L66-L124).

**Comment by gabrielfior** [comment]
Thanks @Adamantios - any reason why checking past redemptions via subgraph is preferred over events?

**Comment by Adamantios** [comment]
@gabrielfior Yes, the redemptions via the subgraph are much faster than parsing all the related on-chain events. The older a service is the more this time increases until it becomes unsustainable both in terms of time and number of required requests to the RPC.

However, an operator can still choose to disable subgraph redemptions via the [USE_SUBGRAPH_FOR_REDEEMING](https://github.com/valory-xyz/trader/blob/v0.12.8/packages/valory/services/trader/service.yaml#L116) configuration.
