### ISSUE TITLE
Cannot update policy if tool index is removed

### ISSUE THREAD

**Issue by jhehemann** [valory-xyz/trader#274]
The policy is updated using tool indexes. The trader raises an error if it tries to add a reward to a tool index that does not exist.
This happens when there are active bets based on predictions from a mech tool and this tool is removed.  Some changes to the mech tools (order), while there are unclosed bets, causes a wrong update of the policy and potential errors.

https://github.com/valory-xyz/trader/blob/04f46fabdc08ed595ddb47968d34f673d8b0620a/packages/valory/skills/decision_maker_abci/behaviours/reedem.py#L125

**Comment by Adamantios** [comment]
Thanks, we are aware of this issue and working on a fix.
